# Generated by Django 3.2.5 on 2023-08-11 14:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('pfimg', models.ImageField(default='apl.png', upload_to='Profiles/')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('0', '--- Select Your Gender ---'), ('1', 'Male'), ('2', 'Female')], default='0', max_length=5)),
                ('role_type', models.CharField(choices=[('0', 'Guest'), ('1', 'Recruiter'), ('2', 'Applicant')], default='0', max_length=5)),
                ('desg', models.CharField(choices=[('0', 'General'), ('1', 'Super')], default='0', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RcProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField()),
                ('c_name', models.CharField(default=None, max_length=20)),
                ('est_year', models.CharField(max_length=4)),
                ('Owner', models.CharField(max_length=20)),
                ('rstatus', models.BooleanField(default=False)),
                ('cert', models.FileField(default='proof.png', upload_to='Attachments/')),
                ('rc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.CharField(max_length=20)),
                ('end_date', models.DateTimeField()),
                ('p_date', models.DateTimeField(auto_now_add=True)),
                ('requirements', models.TextField()),
                ('j_status', models.CharField(choices=[('o', 'Opened'), ('c', 'Closed')], default='o', max_length=5)),
                ('salary', models.IntegerField(default=3)),
                ('description', models.CharField(max_length=500)),
                ('jb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField()),
                ('degree', models.CharField(choices=[('0', '--Choose your degree '), ('1', 'B-tech'), ('2', 'M-tech'), ('3', 'MBA'), ('4', 'PG')], max_length=10)),
                ('college', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=150)),
                ('astatus', models.BooleanField(default=False)),
                ('cert', models.FileField(default='valid.png', upload_to='Attachments/')),
                ('ac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_status', models.CharField(choices=[('vp', 'Verification Pending'), ('v', 'Verified'), ('s', 'Selected'), ('d', 'Declined')], default='vp', max_length=10)),
                ('app_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='Attachments/')),
                ('desc', models.CharField(max_length=200)),
                ('ab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='App ID+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job ID+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
